const colors = {
  light: {
    text: "#1A1A1A",
    tint: "#1D6FE0",
    background: "#FAF8F5",
    foreground: "#1A1A1A",
    card: "#FFFFFF",
    cardForeground: "#1A1A1A",
    primary: "#1A1A1A",
    primaryForeground: "#FFFFFF",
    secondary: "#F0EDE8",
    secondaryForeground: "#1A1A1A",
    muted: "#F0EDE8",
    mutedForeground: "#9A9691",
    accent: "#1D6FE0",
    accentForeground: "#FFFFFF",
    destructive: "#E53935",
    destructiveForeground: "#FFFFFF",
    border: "#E8E4DF",
    input: "#E8E4DF",
    success: "#2E7D32",
    warning: "#F57C00",
  },
  dark: {
    text: "#F5F3F0",
    tint: "#4D8EF0",
    background: "#0D0D0D",
    foreground: "#F5F3F0",
    card: "#1A1A1A",
    cardForeground: "#F5F3F0",
    primary: "#FFFFFF",
    primaryForeground: "#0D0D0D",
    secondary: "#262626",
    secondaryForeground: "#F5F3F0",
    muted: "#1F1F1F",
    mutedForeground: "#6A6560",
    accent: "#4D8EF0",
    accentForeground: "#FFFFFF",
    destructive: "#EF5350",
    destructiveForeground: "#FFFFFF",
    border: "#2A2A2A",
    input: "#2A2A2A",
    success: "#4CAF50",
    warning: "#FF9800",
  },
  radius: 12,
};

export default colors;
