kind = "web"
previewPath = "/"
title = "Website"
version = "1.0.0"
id = "artifacts/website"

[[services]]
localPort = 3000
name = "Website"
paths = ["/"]

[services.development]
run = "pnpm --filter @workspace/website run dev"

[services.env]
PORT = "3000"
